/* INSERT nas tabelas */


/* Tabela Api */

INSERT INTO API (ID, NAME)
VALUES (1, 'Marcos');
INSERT INTO API (ID, NAME)
VALUES (2, 'JAMEF');
INSERT INTO API (ID, NAME)
VALUES (3, 'RTE');
INSERT INTO API (ID, NAME)
VALUES (4, 'GBC');

/* Tabela Client */
INSERT INTO CLIENT (ID, EMAIL, PASSWORD, ACCESSTOKEN, DOCUMENT, NAME, PHONE)
VALUES ( 1, 'marcosss@teste.com', 'marcossenha', 'atoken', '10012196002', 'marcos', 887988898);
INSERT INTO CLIENT (ID, EMAIL, PASSWORD, ACCESSTOKEN, DOCUMENT, NAME, PHONE)
VALUES ( 2, 'ana@hotmail.com', '123ana', 'atoken', '83579930010', 'ana', 998877665);
INSERT INTO CLIENT (ID, EMAIL, PASSWORD, ACCESSTOKEN, DOCUMENT, NAME, PHONE)
VALUES ( 3, 'anaf@hotmail.com', '12345678', 'atoken', '83573430010', 'anaf', 998800665);

/* Tabela ClientApi */
INSERT INTO CLIENTAPI (CLIENTID, APIID, USERNAME, PASSWORD)
VALUES(1, 1, 'Marcos', 'marcossenha');


/* Tabela ClientConfiguration */
/*Correto*/
INSERT INTO CLIENTCONFIGURATION (CLIENTID, SMTPHOST, SMTPUSERNAME, SMTPPASSWORD, SMTPPORT, TRAKINGEMAILTEMPLATE, TRAKINGEMAILEVENTTEMPLATE)
VALUES (1, 'smtphost', 'usersmtp', 'senhasmtp', 2, 'traking@email', 'trakingemail@event');

/*Tabela Plan*/
INSERT INTO [PLAN] (ID, NAME,REQUESTSQUANTITY,PRICE) VALUES (1,'APP20',100,330.00);
INSERT INTO [PLAN] (ID, NAME,REQUESTSQUANTITY,PRICE) VALUES (2,'APP21',200,30.00);

/*Tabela ClientPlanHistory*/
INSERT INTO CLIENTPLANHISTORY (ID,CLIENTID,PLANID,[START],[END]) VALUES (1,1,1,'30-09-2020','');
INSERT INTO CLIENTPLANHISTORY (ID,CLIENTID,PLANID,[START],[END]) VALUES (2,1,2,'30-11-2018','30-11-2020');

/*Tabela ClientPlan*/
INSERT INTO CLIENTPLAN (CLIENTID,PLANID,SMSCREDITS) VALUES (1,1,100);

/* Tabela ClientApiRequest */
INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (1,1,1,'26-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (2,1,1,'26-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (3,1,1,'26-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (4,1,1,'26-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (5,1,1,'27-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (6,1,1,'27-10-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (7,1,1,'28-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (8,1,1,'28-10-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (9,1,1,'29-10-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (10,1,1,'30-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (11,1,1,'30-10-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (12,1,1,'28-10-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (13,1,1,'28-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (14,1,1,'31-10-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (15,1,1,'25-10-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (16,1,1,'25-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (17,1,1,'28-10-2020','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (18,1,1,'01-11-2019','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (19,1,1,'01-11-2019','/api/sms/send', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (20,1,1,'25-11-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (21,1,1,'25-11-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (22,1,1,'25-11-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (23,1,1,'25-11-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (24,1,1,'25-12-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (25,1,1,'25-09-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (26,1,1,'25-12-2020','urlrequest', 'messagebody',1,'200','postact');

INSERT INTO CLIENTAPIREQUEST (ID,CLIENTID,PLANID,DTREQUEST,URL,BODY,RESPONSESTATUS,RESPONSEBODY,POSTACTIONS)
VALUES (27,1,1,'25-09-2020','urlrequest', 'messagebody',1,'200','postact');